### ISSUE TITLE
comprehension of sort

### ISSUE THREAD

**Issue by as142** [mymaor89/TeleCollege#1]
Hi there, When I was learning and trying to understand the function "sort" in TeleCollege/algorithms/algorithms/sorting/bogo_sort.py, I was confused about the description of its delivered function. My understanding of this code snippet is "takes a list of integers and sorts them in ascending order". Do I understand that right?

**Comment by onlugassy** [comment]
Hi, 

I'm sorry but my team and I did not code these algorithms(the entire "algorithms" directory), they were taken from the web and used just for the sake of brainstorming and testing different options. The project itself was not done in python but in C++ and C# instead, so I apologize but I cannot be of help to you.

good luck.
